using System.Text;

namespace Spider8DAQ.Core.Export;

/// <summary>
/// Writes a MATLAB Level-4 compatible .mat with one real double matrix "data" (rows=samples, cols=channels)
/// and a companion .m script listing channel names.
/// </summary>
public static class MatExporter
{
    public static void Export(
        string matPath,
        IReadOnlyList<string> channelNames,
        IReadOnlyList<double[]> columnMajorValues)
    {
        if (columnMajorValues.Count == 0)
            throw new ArgumentException("No channels to export.");

        var rows = columnMajorValues[0].Length;
        var cols = columnMajorValues.Count;
        Directory.CreateDirectory(Path.GetDirectoryName(Path.GetFullPath(matPath))!);

        using (var fs = File.Create(matPath))
        using (var bw = new BinaryWriter(fs))
        {
            // Level 4 numeric matrix header for variable "data"
            // type: 0 = little-endian double (IEEE)
            const int type = 0;
            bw.Write(type);
            bw.Write(rows);
            bw.Write(cols);
            bw.Write(0); // imagf = 0 (real)
            var nameBytes = Encoding.ASCII.GetBytes("data");
            bw.Write(nameBytes.Length + 1);
            bw.Write(nameBytes);
            bw.Write((byte)0);

            // Column-major for MATLAB
            for (var c = 0; c < cols; c++)
            {
                var col = columnMajorValues[c];
                for (var r = 0; r < rows; r++)
                {
                    var v = r < col.Length ? col[r] : double.NaN;
                    bw.Write(v);
                }
            }
        }

        var scriptPath = Path.ChangeExtension(matPath, ".m");
        var sb = new StringBuilder();
        sb.AppendLine("% Auto-generated by UPET AcqLab");
        sb.AppendLine($"% load('{Path.GetFileName(matPath)}');");
        sb.AppendLine("channelNames = {");
        foreach (var name in channelNames)
            sb.AppendLine($"    '{name.Replace("'", "''")}';");
        sb.AppendLine("};");
        File.WriteAllText(scriptPath, sb.ToString(), Encoding.UTF8);
    }

    public static void ExportFromColumnLists(
        string matPath,
        IReadOnlyList<string> names,
        IReadOnlyList<IReadOnlyList<double>> columns)
    {
        var arrays = columns.Select(c => c.ToArray()).ToArray();
        Export(matPath, names, arrays);
    }
}
